<?php

class PaysTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('pays')->truncate();

		$pays = array(
			  array('code' => 'AF','nom' => 'Afghanistan'),
			  array('code' => 'ZA','nom' => 'Afrique du Sud'),
			  array('code' => 'AL','nom' => 'Albanie'),
			  array('code' => 'DZ','nom' => 'Algérie'),
			  array('code' => 'DE','nom' => 'Allemagne'),
			  array('code' => 'AD','nom' => 'Andorre'),
			  array('code' => 'AO','nom' => 'Angola'),
			  array('code' => 'AI','nom' => 'Anguilla'),
			  array('code' => 'AQ','nom' => 'Antarctique'),
			  array('code' => 'AG','nom' => 'Antigua-et-Barbuda'),
			  array('code' => 'AN','nom' => 'Antilles néerlandaises'),
			  array('code' => 'SA','nom' => 'Arabie saoudite'),
			  array('code' => 'AR','nom' => 'Argentine'),
			  array('code' => 'AM','nom' => 'Arménie'),
			  array('code' => 'AW','nom' => 'Aruba'),
			  array('code' => 'AU','nom' => 'Australie'),
			  array('code' => 'AT','nom' => 'Autriche'),
			  array('code' => 'AZ','nom' => 'Azerbaïdjan'),
			  array('code' => 'BJ','nom' => 'Bénin'),
			  array('code' => 'BS','nom' => 'Bahamas'),
			  array('code' => 'BH','nom' => 'Bahreïn'),
			  array('code' => 'BD','nom' => 'Bangladesh'),
			  array('code' => 'BB','nom' => 'Barbade'),
			  array('code' => 'PW','nom' => 'Belau'),
			  array('code' => 'BE','nom' => 'Belgique'),
			  array('code' => 'BZ','nom' => 'Belize'),
			  array('code' => 'BM','nom' => 'Bermudes'),
			  array('code' => 'BT','nom' => 'Bhoutan'),
			  array('code' => 'BY','nom' => 'Biélorussie'),
			  array('code' => 'MM','nom' => 'Birmanie'),
			  array('code' => 'BO','nom' => 'Bolivie'),
			  array('code' => 'BA','nom' => 'Bosnie-Herzégovine'),
			  array('code' => 'BW','nom' => 'Botswana'),
			  array('code' => 'BR','nom' => 'Brésil'),
			  array('code' => 'BN','nom' => 'Brunei'),
			  array('code' => 'BG','nom' => 'Bulgarie'),
			  array('code' => 'BF','nom' => 'Burkina Faso'),
			  array('code' => 'BI','nom' => 'Burundi'),
			  array('code' => 'CI','nom' => 'Côte d\'Ivoire'),
			  array('code' => 'KH','nom' => 'Cambodge'),
			  array('code' => 'CM','nom' => 'Cameroun'),
			  array('code' => 'CA','nom' => 'Canada'),
			  array('code' => 'CV','nom' => 'Cap-Vert'),
			  array('code' => 'CL','nom' => 'Chili'),
			  array('code' => 'CN','nom' => 'Chine'),
			  array('code' => 'CY','nom' => 'Chypre'),
			  array('code' => 'CO','nom' => 'Colombie'),
			  array('code' => 'KM','nom' => 'Comores'),
			  array('code' => 'CG','nom' => 'Congo'),
			  array('code' => 'KP','nom' => 'Corée du Nord'),
			  array('code' => 'KR','nom' => 'Corée du Sud'),
			  array('code' => 'CR','nom' => 'Costa Rica'),
			  array('code' => 'HR','nom' => 'Croatie'),
			  array('code' => 'CU','nom' => 'Cuba'),
			  array('code' => 'DK','nom' => 'Danemark'),
			  array('code' => 'DJ','nom' => 'Djibouti'),
			  array('code' => 'DM','nom' => 'Dominique'),
			  array('code' => 'EG','nom' => 'Égypte'),
			  array('code' => 'AE','nom' => 'Émirats arabes unis'),
			  array('code' => 'EC','nom' => 'Équateur'),
			  array('code' => 'ER','nom' => 'Érythrée'),
			  array('code' => 'ES','nom' => 'Espagne'),
			  array('code' => 'EE','nom' => 'Estonie'),
			  array('code' => 'US','nom' => 'États-Unis'),
			  array('code' => 'ET','nom' => 'Éthiopie'),
			  array('code' => 'FI','nom' => 'Finlande'),
			  array('code' => 'FR','nom' => 'France'),
			  array('code' => 'GE','nom' => 'Géorgie'),
			  array('code' => 'GA','nom' => 'Gabon'),
			  array('code' => 'GM','nom' => 'Gambie'),
			  array('code' => 'GH','nom' => 'Ghana'),
			  array('code' => 'GI','nom' => 'Gibraltar'),
			  array('code' => 'GR','nom' => 'Grèce'),
			  array('code' => 'GD','nom' => 'Grenade'),
			  array('code' => 'GL','nom' => 'Groenland'),
			  array('code' => 'GP','nom' => 'Guadeloupe'),
			  array('code' => 'GU','nom' => 'Guam'),
			  array('code' => 'GT','nom' => 'Guatemala'),
			  array('code' => 'GN','nom' => 'Guinée'),
			  array('code' => 'GQ','nom' => 'Guinée équatoriale'),
			  array('code' => 'GW','nom' => 'Guinée-Bissao'),
			  array('code' => 'GY','nom' => 'Guyana'),
			  array('code' => 'GF','nom' => 'Guyane française'),
			  array('code' => 'HT','nom' => 'Haïti'),
			  array('code' => 'HN','nom' => 'Honduras'),
			  array('code' => 'HK','nom' => 'Hong Kong'),
			  array('code' => 'HU','nom' => 'Hongrie'),
			  array('code' => 'BV','nom' => 'Ile Bouvet'),
			  array('code' => 'CX','nom' => 'Ile Christmas'),
			  array('code' => 'NF','nom' => 'Ile Norfolk'),
			  array('code' => 'KY','nom' => 'Iles Cayman'),
			  array('code' => 'CK','nom' => 'Iles Cook'),
			  array('code' => 'FO','nom' => 'Iles Féroé'),
			  array('code' => 'FK','nom' => 'Iles Falkland'),
			  array('code' => 'FJ','nom' => 'Iles Fidji'),
			  array('code' => 'GS','nom' => 'Iles Géorgie du Sud et Sandwich du Sud'),
			  array('code' => 'HM','nom' => 'Iles Heard et McDonald'),
			  array('code' => 'MH','nom' => 'Iles Marshall'),
			  array('code' => 'PN','nom' => 'Iles Pitcairn'),
			  array('code' => 'SB','nom' => 'Iles Salomon'),
			  array('code' => 'SJ','nom' => 'Iles Svalbard et Jan Mayen'),
			  array('code' => 'TC','nom' => 'Iles Turks-et-Caicos'),
			  array('code' => 'VI','nom' => 'Iles Vierges américaines'),
			  array('code' => 'VG','nom' => 'Iles Vierges britanniques'),
			  array('code' => 'CC','nom' => 'Iles des Cocos (Keeling)'),
			  array('code' => 'UM','nom' => 'Iles mineures éloignées des États-Unis'),
			  array('code' => 'IN','nom' => 'Inde'),
			  array('code' => 'ID','nom' => 'Indonésie'),
			  array('code' => 'IR','nom' => 'Iran'),
			  array('code' => 'IQ','nom' => 'Iraq'),
			  array('code' => 'IE','nom' => 'Irlande'),
			  array('code' => 'IS','nom' => 'Islande'),
			  array('code' => 'IL','nom' => 'Israël'),
			  array('code' => 'IT','nom' => 'Italie'),
			  array('code' => 'JM','nom' => 'Jamaïque'),
			  array('code' => 'JP','nom' => 'Japon'),
			  array('code' => 'JO','nom' => 'Jordanie'),
			  array('code' => 'KZ','nom' => 'Kazakhstan'),
			  array('code' => 'KE','nom' => 'Kenya'),
			  array('code' => 'KG','nom' => 'Kirghizistan'),
			  array('code' => 'KI','nom' => 'Kiribati'),
			  array('code' => 'KW','nom' => 'Koweït'),
			  array('code' => 'LA','nom' => 'Laos'),
			  array('code' => 'LS','nom' => 'Lesotho'),
			  array('code' => 'LV','nom' => 'Lettonie'),
			  array('code' => 'LB','nom' => 'Liban'),
			  array('code' => 'LR','nom' => 'Liberia'),
			  array('code' => 'LY','nom' => 'Libye'),
			  array('code' => 'LI','nom' => 'Liechtenstein'),
			  array('code' => 'LT','nom' => 'Lituanie'),
			  array('code' => 'LU','nom' => 'Luxembourg'),
			  array('code' => 'MO','nom' => 'Macao'),
			  array('code' => 'MG','nom' => 'Madagascar'),
			  array('code' => 'MY','nom' => 'Malaisie'),
			  array('code' => 'MW','nom' => 'Malawi'),
			  array('code' => 'MV','nom' => 'Maldives'),
			  array('code' => 'ML','nom' => 'Mali'),
			  array('code' => 'MT','nom' => 'Malte'),
			  array('code' => 'MP','nom' => 'Mariannes du Nord'),
			  array('code' => 'MA','nom' => 'Maroc'),
			  array('code' => 'MQ','nom' => 'Martinique'),
			  array('code' => 'MU','nom' => 'Maurice'),
			  array('code' => 'MR','nom' => 'Mauritanie'),
			  array('code' => 'YT','nom' => 'Mayotte'),
			  array('code' => 'MX','nom' => 'Mexique'),
			  array('code' => 'FM','nom' => 'Micronésie'),
			  array('code' => 'MD','nom' => 'Moldavie'),
			  array('code' => 'MC','nom' => 'Monaco'),
			  array('code' => 'MN','nom' => 'Mongolie'),
			  array('code' => 'MS','nom' => 'Montserrat'),
			  array('code' => 'MZ','nom' => 'Mozambique'),
			  array('code' => 'NP','nom' => 'Népal'),
			  array('code' => 'NA','nom' => 'Namibie'),
			  array('code' => 'NR','nom' => 'Nauru'),
			  array('code' => 'NI','nom' => 'Nicaragua'),
			  array('code' => 'NE','nom' => 'Niger'),
			  array('code' => 'NG','nom' => 'Nigeria'),
			  array('code' => 'NU','nom' => 'Nioué'),
			  array('code' => 'NO','nom' => 'Norvège'),
			  array('code' => 'NC','nom' => 'Nouvelle-Calédonie'),
			  array('code' => 'NZ','nom' => 'Nouvelle-Zélande'),
			  array('code' => 'OM','nom' => 'Oman'),
			  array('code' => 'UG','nom' => 'Ouganda'),
			  array('code' => 'UZ','nom' => 'Ouzbékistan'),
			  array('code' => 'PE','nom' => 'Pérou'),
			  array('code' => 'PK','nom' => 'Pakistan'),
			  array('code' => 'PA','nom' => 'Panama'),
			  array('code' => 'PG','nom' => 'Papouasie-Nouvelle-Guinée'),
			  array('code' => 'PY','nom' => 'Paraguay'),
			  array('code' => 'NL','nom' => 'Pays-Bas'),
			  array('code' => 'PH','nom' => 'Philippines'),
			  array('code' => 'PL','nom' => 'Pologne'),
			  array('code' => 'PF','nom' => 'Polynésie française'),
			  array('code' => 'PR','nom' => 'Porto Rico'),
			  array('code' => 'PT','nom' => 'Portugal'),
			  array('code' => 'QA','nom' => 'Qatar'),
			  array('code' => 'CF','nom' => 'République centrafricaine'),
			  array('code' => 'CD','nom' => 'République démocratique du Congo'),
			  array('code' => 'DO','nom' => 'République dominicaine'),
			  array('code' => 'CZ','nom' => 'République tchèque'),
			  array('code' => 'RE','nom' => 'Réunion'),
			  array('code' => 'RO','nom' => 'Roumanie'),
			  array('code' => 'GB','nom' => 'Royaume-Uni'),
			  array('code' => 'RU','nom' => 'Russie'),
			  array('code' => 'RW','nom' => 'Rwanda'),
			  array('code' => 'SN','nom' => 'Sénégal'),
			  array('code' => 'EH','nom' => 'Sahara occidental'),
			  array('code' => 'KN','nom' => 'Saint-Christophe-et-Niévès'),
			  array('code' => 'SM','nom' => 'Saint-Marin'),
			  array('code' => 'PM','nom' => 'Saint-Pierre-et-Miquelon'),
			  array('code' => 'VA','nom' => 'Saint-Siège '),
			  array('code' => 'VC','nom' => 'Saint-Vincent-et-les-Grenadines'),
			  array('code' => 'SH','nom' => 'Sainte-Hélène'),
			  array('code' => 'LC','nom' => 'Sainte-Lucie'),
			  array('code' => 'SV','nom' => 'Salvador'),
			  array('code' => 'WS','nom' => 'Samoa'),
			  array('code' => 'AS','nom' => 'Samoa américaines'),
			  array('code' => 'ST','nom' => 'Sao Tomé-et-Principe'),
			  array('code' => 'SC','nom' => 'Seychelles'),
			  array('code' => 'SL','nom' => 'Sierra Leone'),
			  array('code' => 'SG','nom' => 'Singapour'),
			  array('code' => 'SI','nom' => 'Slovénie'),
			  array('code' => 'SK','nom' => 'Slovaquie'),
			  array('code' => 'SO','nom' => 'Somalie'),
			  array('code' => 'SD','nom' => 'Soudan'),
			  array('code' => 'LK','nom' => 'Sri Lanka'),
			  array('code' => 'SE','nom' => 'Suède'),
			  array('code' => 'CH','nom' => 'Suisse'),
			  array('code' => 'SR','nom' => 'Suriname'),
			  array('code' => 'SZ','nom' => 'Swaziland'),
			  array('code' => 'SY','nom' => 'Syrie'),
			  array('code' => 'TW','nom' => 'Taïwan'),
			  array('code' => 'TJ','nom' => 'Tadjikistan'),
			  array('code' => 'TZ','nom' => 'Tanzanie'),
			  array('code' => 'TD','nom' => 'Tchad'),
			  array('code' => 'TF','nom' => 'Terres australes françaises'),
			  array('code' => 'IO','nom' => 'Territoire britannique de l\'Océan Indien'),
			  array('code' => 'TH','nom' => 'Thaïlande'),
			  array('code' => 'TL','nom' => 'Timor Oriental'),
			  array('code' => 'TG','nom' => 'Togo'),
			  array('code' => 'TK','nom' => 'Tokélaou'),
			  array('code' => 'TO','nom' => 'Tonga'),
			  array('code' => 'TT','nom' => 'Trinité-et-Tobago'),
			  array('code' => 'TN','nom' => 'Tunisie'),
			  array('code' => 'TM','nom' => 'Turkménistan'),
			  array('code' => 'TR','nom' => 'Turquie'),
			  array('code' => 'TV','nom' => 'Tuvalu'),
			  array('code' => 'UA','nom' => 'Ukraine'),
			  array('code' => 'UY','nom' => 'Uruguay'),
			  array('code' => 'VU','nom' => 'Vanuatu'),
			  array('code' => 'VE','nom' => 'Venezuela'),
			  array('code' => 'VN','nom' => 'Viêtnam'),
			  array('code' => 'WF','nom' => 'Wallis-et-Futuna'),
			  array('code' => 'YE','nom' => 'Yémen'),
			  array('code' => 'YU','nom' => 'Yougoslavie'),
			  array('code' => 'ZM','nom' => 'Zambie'),
			  array('code' => 'ZW','nom' => 'Zimbabwe'),
			  array('code' => 'MK','nom' => 'ex-République yougoslave de Macédoine')
		);

		// Uncomment the below to run the seeder
		DB::table('pays')->insert($pays);
	}

}
